name: 'Web Audit Report'
description: 'Genera un reporte de auditoría usando npm audit y lo publica'
author: 'ElJijuna'
inputs:
  runtime:
    description: 'Runtime: npm | bun | pnpm | yarn'
    required: true
    default: 'npm'
  report_name:
    description: 'Nombre base del archivo de reporte'
    required: true
    default: 'react-base-app'
runs:
  using: 'composite'
  steps:
    - name: 📥 Clonar el repositorio
      uses: actions/checkout@v3

    - name: 🔧 Instalar dependencias
      run: npm ci
      shell: bash

    - name: 🧨 Ejecutar script
      run: |
        curl https://raw.githubusercontent.com/ElJijuna/Bash-Scripts/main/web-audit-report.sh | bash -s ${{ inputs.runtime }} ${{ inputs.report_name }}
      shell: bash

    - name: 📦 Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: audit-report
        path: ${{ inputs.report_name }}--web-audit.json
